layout_spectrum: 0.7951798767359504
typography_spectrum: 0.8405327894486081
color:
  lightness: 0.6396777199149722
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  saturation: 0.5597341192171605
  brandStrength: 0.29874047643864654
  rhythmicContrast: 0.1392169610912552
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1db6479-6ddc-434d-a3c2-cadc66eb1ee4.jpg
analytics:
  facebook: '577111065790019'
  google: UA-78630107-1
author:
  name: Yana Syrkin
  url: 'http://yanasyrkin.com'
  email: yana.syrkin@gmail.com
name: '#yanasyrkin'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: 1e304668-14d6-44b2-83ca-3471ba0f5aea
    type: content
  - name: Creator of Pet Couture
    id: be3346ae-a36c-4aaf-9a35-bc41fc2d72e8
    type: content
  - name: Hollywood Custom Designer
    id: 2b7159d6-43c1-41bd-a85a-103254d34227
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/daf87189-231c-4bc8-82fa-46df1ee7a73b.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
description: ''
purpose: []
