typography_spectrum: 0.1539090990554541
content_rating:
  adult: false
color:
  lightness: 0.5230885273776948
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.2560955060180277
  brandStrength: 0.02050549443811178
  rhythmicContrast: 0.4151824086438864
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1db6479-6ddc-434d-a3c2-cadc66eb1ee4.jpg
layout_spectrum: 0.9170213
analytics:
  facebook: '577111065790019'
  google: UA-78630107-1
author:
  name: Yana Syrkin
  url: 'http://yanasyrkin.com'
  email: yana.syrkin@gmail.com
name: '#yanasyrkin'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About/Contact
    id: 1e304668-14d6-44b2-83ca-3471ba0f5aea
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/daf87189-231c-4bc8-82fa-46df1ee7a73b.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: custom designer + fairy dogmother
content: []
description: custom designer + fairy dogmother
purpose: []
