typography_spectrum: 0.15390909905545413
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.020505494438111782
  lightness: 0.5230885273776948
  saturation: 0.25609550601802766
  rhythmicContrast: 0.41518240864388645
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1db6479-6ddc-434d-a3c2-cadc66eb1ee4.jpg'
  type: null
  appId: null
layout_spectrum: 0.7300717872567475
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Yana Syrkin
  email: yana.syrkin@gmail.com
  url: 'http://yanasyrkin.com'
logo: null
name: yana syrkin
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/daf87189-231c-4bc8-82fa-46df1ee7a73b.jpg'
title: costume designer + fairy dogmother
purpose: []
